### ISSUE TITLE
Gps and Region

### ISSUE THREAD

**Issue by bttfw** [kritch83/T-BeamHeliumMapper#1]
Hi
Where can we set the region of the mapper ?

And I can only get gps working if I modify the code is anyone else having that problem

thanks for your help

**Comment by Hagbard89** [comment]
i have the same issue, how did you modify the code to get the gps to work? in my case, it blinks red but get no satelites

**Comment by kritch83** [comment]
Let me take a look today after work.  I'll see what's going on.  Thanks

**Comment by Hagbard89** [comment]
i fixed it with a GPS Reset script from Lilygo, i used option 3 from this fork:  

https://github.com/eriktheV-king/TTGO_T-beam_GPS-reset

after that my GPS found the satelites nearly instant!
but i think the wrong region is set... i got 9 satelites but no messages where transmited. im near @ a helium hotspot/miner.
is there a option in the code to change the region? I didn't find the part to change that. I need EU 868mhz

**Comment by kritch83** [comment]
Here is the additional code you need to put in the ttn file I believe.  I have no way to test this so not sure if this will do it or not.  Make sure you comment out the US915 part for selecting the sub band.This is for Europe.  Checkout https://github.com/sustakat/helium-mapper-tbeam to see more examples.

`LMIC_setupChannel(0, 868100000, DR_RANGE_MAP(DR_SF12, DR_SF7),  BAND_CENTI);      // g-band`
 ` LMIC_setupChannel(1, 868300000, DR_RANGE_MAP(DR_SF12, DR_SF7B), BAND_CENTI);      // g-band`
  `LMIC_setupChannel(2, 868500000, DR_RANGE_MAP(DR_SF12, DR_SF7),  BAND_CENTI);      // g-band`
  `LMIC_setupChannel(3, 867100000, DR_RANGE_MAP(DR_SF12, DR_SF7),  BAND_CENTI);      // g-band`
  `LMIC_setupChannel(4, 867300000, DR_RANGE_MAP(DR_SF12, DR_SF7),  BAND_CENTI);      // g-band`
 ` LMIC_setupChannel(5, 867500000, DR_RANGE_MAP(DR_SF12, DR_SF7),  BAND_CENTI);      // g-band`
 ` LMIC_setupChannel(6, 867700000, DR_RANGE_MAP(DR_SF12, DR_SF7),  BAND_CENTI);      // g-band`
 ` LMIC_setupChannel(7, 867900000, DR_RANGE_MAP(DR_SF12, DR_SF7),  BAND_CENTI);      // g-band`
 ` LMIC_setupChannel(8, 868800000, DR_RANGE_MAP(DR_FSK,  DR_FSK),  BAND_MILLI);      // g2-band`

**Comment by Hagbard89** [comment]
Thx! This section is allready in the code, i have commented out the US and AU part. But i still can't transmit messages and helium join failed. Maybe the Hotspot isn't setup correctly. Tomorow i'm in a city with a lot of Hotspots around. i will test it again then.

**Comment by Hagbard89** [comment]
is there something i should change in the decoder when i'm in the EU?

**Comment by Hagbard89** [comment]
I finaly got it! I changed the Arduino\libraries\MCCI_LoRaWAN_LMIC_library\project_config.h , uncomment #define CFG_eu868 1 and it works in EU!
